[package]
name = "monkey"
description = "The Monkey Programming language"
version = "0.3.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
byteorder = "1.4.3"

[features]
debug_print_code = []
debug_trace_execution = []
# default = ["debug_trace_execution"]
